[package]
name = "mirrord-operator"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
edition.workspace = true


[features]
default = []
server = ["protocol"]
client = ["protocol", "dep:futures", "dep:mirrord-kube", "dep:mirrord-progress"]
protocol = ["dep:actix-codec", "dep:bincode", "dep:bytes",  "dep:mirrord-config", "dep:mirrord-protocol"]

[dependencies]
mirrord-config = { path = "../config", optional = true }
mirrord-kube = { path = "../kube", optional = true }
mirrord-progress = { path = "../progress", optional = true }
mirrord-protocol = { path = "../protocol", optional = true }

async-trait = "0.1"
actix-codec = { workspace = true, optional = true }
bincode =  { version = "2.0.0-rc.2", features = ["serde"], optional = true }
bytes = { workspace = true, optional = true }
k8s-openapi.workspace = true
kube.workspace = true
futures = { workspace = true, optional = true }
schemars = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json.workspace = true
serde_yaml = "0.9"
thiserror.workspace = true
tokio.workspace = true
