// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `proto/tcp.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:protocol.NewTcpConnection)
pub struct NewTcpConnection {
    // message fields
    // @@protoc_insertion_point(field:protocol.NewTcpConnection.connection_id)
    pub connection_id: u64,
    // @@protoc_insertion_point(field:protocol.NewTcpConnection.remote_address)
    pub remote_address: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:protocol.NewTcpConnection.destination_port)
    pub destination_port: i32,
    // @@protoc_insertion_point(field:protocol.NewTcpConnection.source_port)
    pub source_port: i32,
    // @@protoc_insertion_point(field:protocol.NewTcpConnection.local_address)
    pub local_address: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:protocol.NewTcpConnection.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NewTcpConnection {
    fn default() -> &'a NewTcpConnection {
        <NewTcpConnection as ::protobuf::Message>::default_instance()
    }
}

impl NewTcpConnection {
    pub fn new() -> NewTcpConnection {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "connection_id",
            |m: &NewTcpConnection| { &m.connection_id },
            |m: &mut NewTcpConnection| { &mut m.connection_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "remote_address",
            |m: &NewTcpConnection| { &m.remote_address },
            |m: &mut NewTcpConnection| { &mut m.remote_address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "destination_port",
            |m: &NewTcpConnection| { &m.destination_port },
            |m: &mut NewTcpConnection| { &mut m.destination_port },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "source_port",
            |m: &NewTcpConnection| { &m.source_port },
            |m: &mut NewTcpConnection| { &mut m.source_port },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "local_address",
            |m: &NewTcpConnection| { &m.local_address },
            |m: &mut NewTcpConnection| { &mut m.local_address },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NewTcpConnection>(
            "NewTcpConnection",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NewTcpConnection {
    const NAME: &'static str = "NewTcpConnection";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.connection_id = is.read_uint64()?;
                },
                18 => {
                    self.remote_address = is.read_bytes()?;
                },
                24 => {
                    self.destination_port = is.read_int32()?;
                },
                32 => {
                    self.source_port = is.read_int32()?;
                },
                42 => {
                    self.local_address = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.connection_id != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.connection_id);
        }
        if !self.remote_address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.remote_address);
        }
        if self.destination_port != 0 {
            my_size += ::protobuf::rt::int32_size(3, self.destination_port);
        }
        if self.source_port != 0 {
            my_size += ::protobuf::rt::int32_size(4, self.source_port);
        }
        if !self.local_address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.local_address);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.connection_id != 0 {
            os.write_uint64(1, self.connection_id)?;
        }
        if !self.remote_address.is_empty() {
            os.write_bytes(2, &self.remote_address)?;
        }
        if self.destination_port != 0 {
            os.write_int32(3, self.destination_port)?;
        }
        if self.source_port != 0 {
            os.write_int32(4, self.source_port)?;
        }
        if !self.local_address.is_empty() {
            os.write_bytes(5, &self.local_address)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NewTcpConnection {
        NewTcpConnection::new()
    }

    fn clear(&mut self) {
        self.connection_id = 0;
        self.remote_address.clear();
        self.destination_port = 0;
        self.source_port = 0;
        self.local_address.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NewTcpConnection {
        static instance: NewTcpConnection = NewTcpConnection {
            connection_id: 0,
            remote_address: ::std::vec::Vec::new(),
            destination_port: 0,
            source_port: 0,
            local_address: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NewTcpConnection {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NewTcpConnection").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NewTcpConnection {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NewTcpConnection {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:protocol.TcpData)
pub struct TcpData {
    // message fields
    // @@protoc_insertion_point(field:protocol.TcpData.connection_id)
    pub connection_id: u64,
    // @@protoc_insertion_point(field:protocol.TcpData.bytes)
    pub bytes: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:protocol.TcpData.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TcpData {
    fn default() -> &'a TcpData {
        <TcpData as ::protobuf::Message>::default_instance()
    }
}

impl TcpData {
    pub fn new() -> TcpData {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "connection_id",
            |m: &TcpData| { &m.connection_id },
            |m: &mut TcpData| { &mut m.connection_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "bytes",
            |m: &TcpData| { &m.bytes },
            |m: &mut TcpData| { &mut m.bytes },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TcpData>(
            "TcpData",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TcpData {
    const NAME: &'static str = "TcpData";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.connection_id = is.read_uint64()?;
                },
                18 => {
                    self.bytes = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.connection_id != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.connection_id);
        }
        if !self.bytes.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.bytes);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.connection_id != 0 {
            os.write_uint64(1, self.connection_id)?;
        }
        if !self.bytes.is_empty() {
            os.write_bytes(2, &self.bytes)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TcpData {
        TcpData::new()
    }

    fn clear(&mut self) {
        self.connection_id = 0;
        self.bytes.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TcpData {
        static instance: TcpData = TcpData {
            connection_id: 0,
            bytes: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TcpData {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TcpData").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TcpData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TcpData {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:protocol.TcpClose)
pub struct TcpClose {
    // message fields
    // @@protoc_insertion_point(field:protocol.TcpClose.connection_id)
    pub connection_id: u64,
    // special fields
    // @@protoc_insertion_point(special_field:protocol.TcpClose.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TcpClose {
    fn default() -> &'a TcpClose {
        <TcpClose as ::protobuf::Message>::default_instance()
    }
}

impl TcpClose {
    pub fn new() -> TcpClose {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "connection_id",
            |m: &TcpClose| { &m.connection_id },
            |m: &mut TcpClose| { &mut m.connection_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TcpClose>(
            "TcpClose",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TcpClose {
    const NAME: &'static str = "TcpClose";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.connection_id = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.connection_id != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.connection_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.connection_id != 0 {
            os.write_uint64(1, self.connection_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TcpClose {
        TcpClose::new()
    }

    fn clear(&mut self) {
        self.connection_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TcpClose {
        static instance: TcpClose = TcpClose {
            connection_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TcpClose {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TcpClose").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TcpClose {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TcpClose {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:protocol.LayerTcp)
pub struct LayerTcp {
    // message oneof groups
    pub inner: ::std::option::Option<layer_tcp::Inner>,
    // special fields
    // @@protoc_insertion_point(special_field:protocol.LayerTcp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LayerTcp {
    fn default() -> &'a LayerTcp {
        <LayerTcp as ::protobuf::Message>::default_instance()
    }
}

impl LayerTcp {
    pub fn new() -> LayerTcp {
        ::std::default::Default::default()
    }

    // int32 port_subscribe = 1;

    pub fn port_subscribe(&self) -> i32 {
        match self.inner {
            ::std::option::Option::Some(layer_tcp::Inner::PortSubscribe(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_port_subscribe(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_port_subscribe(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(layer_tcp::Inner::PortSubscribe(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_port_subscribe(&mut self, v: i32) {
        self.inner = ::std::option::Option::Some(layer_tcp::Inner::PortSubscribe(v))
    }

    // uint64 connection_unsubscribe = 2;

    pub fn connection_unsubscribe(&self) -> u64 {
        match self.inner {
            ::std::option::Option::Some(layer_tcp::Inner::ConnectionUnsubscribe(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_connection_unsubscribe(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_connection_unsubscribe(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(layer_tcp::Inner::ConnectionUnsubscribe(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_connection_unsubscribe(&mut self, v: u64) {
        self.inner = ::std::option::Option::Some(layer_tcp::Inner::ConnectionUnsubscribe(v))
    }

    // int32 port_unsubscribe = 3;

    pub fn port_unsubscribe(&self) -> i32 {
        match self.inner {
            ::std::option::Option::Some(layer_tcp::Inner::PortUnsubscribe(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_port_unsubscribe(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_port_unsubscribe(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(layer_tcp::Inner::PortUnsubscribe(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_port_unsubscribe(&mut self, v: i32) {
        self.inner = ::std::option::Option::Some(layer_tcp::Inner::PortUnsubscribe(v))
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "port_subscribe",
            LayerTcp::has_port_subscribe,
            LayerTcp::port_subscribe,
            LayerTcp::set_port_subscribe,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "connection_unsubscribe",
            LayerTcp::has_connection_unsubscribe,
            LayerTcp::connection_unsubscribe,
            LayerTcp::set_connection_unsubscribe,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "port_unsubscribe",
            LayerTcp::has_port_unsubscribe,
            LayerTcp::port_unsubscribe,
            LayerTcp::set_port_unsubscribe,
        ));
        oneofs.push(layer_tcp::Inner::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LayerTcp>(
            "LayerTcp",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LayerTcp {
    const NAME: &'static str = "LayerTcp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.inner = ::std::option::Option::Some(layer_tcp::Inner::PortSubscribe(is.read_int32()?));
                },
                16 => {
                    self.inner = ::std::option::Option::Some(layer_tcp::Inner::ConnectionUnsubscribe(is.read_uint64()?));
                },
                24 => {
                    self.inner = ::std::option::Option::Some(layer_tcp::Inner::PortUnsubscribe(is.read_int32()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &layer_tcp::Inner::PortSubscribe(v) => {
                    my_size += ::protobuf::rt::int32_size(1, v);
                },
                &layer_tcp::Inner::ConnectionUnsubscribe(v) => {
                    my_size += ::protobuf::rt::uint64_size(2, v);
                },
                &layer_tcp::Inner::PortUnsubscribe(v) => {
                    my_size += ::protobuf::rt::int32_size(3, v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &layer_tcp::Inner::PortSubscribe(v) => {
                    os.write_int32(1, v)?;
                },
                &layer_tcp::Inner::ConnectionUnsubscribe(v) => {
                    os.write_uint64(2, v)?;
                },
                &layer_tcp::Inner::PortUnsubscribe(v) => {
                    os.write_int32(3, v)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LayerTcp {
        LayerTcp::new()
    }

    fn clear(&mut self) {
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LayerTcp {
        static instance: LayerTcp = LayerTcp {
            inner: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LayerTcp {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LayerTcp").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LayerTcp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LayerTcp {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `LayerTcp`
pub mod layer_tcp {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:protocol.LayerTcp.inner)
    pub enum Inner {
        // @@protoc_insertion_point(oneof_field:protocol.LayerTcp.port_subscribe)
        PortSubscribe(i32),
        // @@protoc_insertion_point(oneof_field:protocol.LayerTcp.connection_unsubscribe)
        ConnectionUnsubscribe(u64),
        // @@protoc_insertion_point(oneof_field:protocol.LayerTcp.port_unsubscribe)
        PortUnsubscribe(i32),
    }

    impl ::protobuf::Oneof for Inner {
    }

    impl ::protobuf::OneofFull for Inner {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::LayerTcp as ::protobuf::MessageFull>::descriptor().oneof_by_name("inner").unwrap()).clone()
        }
    }

    impl Inner {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Inner>("inner")
        }
    }
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:protocol.DaemonTcp)
pub struct DaemonTcp {
    // message oneof groups
    pub inner: ::std::option::Option<daemon_tcp::Inner>,
    // special fields
    // @@protoc_insertion_point(special_field:protocol.DaemonTcp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DaemonTcp {
    fn default() -> &'a DaemonTcp {
        <DaemonTcp as ::protobuf::Message>::default_instance()
    }
}

impl DaemonTcp {
    pub fn new() -> DaemonTcp {
        ::std::default::Default::default()
    }

    // .protocol.NewTcpConnection new_tcp_connection = 1;

    pub fn new_tcp_connection(&self) -> &NewTcpConnection {
        match self.inner {
            ::std::option::Option::Some(daemon_tcp::Inner::NewTcpConnection(ref v)) => v,
            _ => <NewTcpConnection as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_new_tcp_connection(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_new_tcp_connection(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(daemon_tcp::Inner::NewTcpConnection(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_new_tcp_connection(&mut self, v: NewTcpConnection) {
        self.inner = ::std::option::Option::Some(daemon_tcp::Inner::NewTcpConnection(v))
    }

    // Mutable pointer to the field.
    pub fn mut_new_tcp_connection(&mut self) -> &mut NewTcpConnection {
        if let ::std::option::Option::Some(daemon_tcp::Inner::NewTcpConnection(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(daemon_tcp::Inner::NewTcpConnection(NewTcpConnection::new()));
        }
        match self.inner {
            ::std::option::Option::Some(daemon_tcp::Inner::NewTcpConnection(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_new_tcp_connection(&mut self) -> NewTcpConnection {
        if self.has_new_tcp_connection() {
            match self.inner.take() {
                ::std::option::Option::Some(daemon_tcp::Inner::NewTcpConnection(v)) => v,
                _ => panic!(),
            }
        } else {
            NewTcpConnection::new()
        }
    }

    // .protocol.TcpData tcp_data = 2;

    pub fn tcp_data(&self) -> &TcpData {
        match self.inner {
            ::std::option::Option::Some(daemon_tcp::Inner::TcpData(ref v)) => v,
            _ => <TcpData as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_tcp_data(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_tcp_data(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(daemon_tcp::Inner::TcpData(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_tcp_data(&mut self, v: TcpData) {
        self.inner = ::std::option::Option::Some(daemon_tcp::Inner::TcpData(v))
    }

    // Mutable pointer to the field.
    pub fn mut_tcp_data(&mut self) -> &mut TcpData {
        if let ::std::option::Option::Some(daemon_tcp::Inner::TcpData(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(daemon_tcp::Inner::TcpData(TcpData::new()));
        }
        match self.inner {
            ::std::option::Option::Some(daemon_tcp::Inner::TcpData(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_tcp_data(&mut self) -> TcpData {
        if self.has_tcp_data() {
            match self.inner.take() {
                ::std::option::Option::Some(daemon_tcp::Inner::TcpData(v)) => v,
                _ => panic!(),
            }
        } else {
            TcpData::new()
        }
    }

    // .protocol.TcpClose tcp_close = 3;

    pub fn tcp_close(&self) -> &TcpClose {
        match self.inner {
            ::std::option::Option::Some(daemon_tcp::Inner::TcpClose(ref v)) => v,
            _ => <TcpClose as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_tcp_close(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_tcp_close(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(daemon_tcp::Inner::TcpClose(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_tcp_close(&mut self, v: TcpClose) {
        self.inner = ::std::option::Option::Some(daemon_tcp::Inner::TcpClose(v))
    }

    // Mutable pointer to the field.
    pub fn mut_tcp_close(&mut self) -> &mut TcpClose {
        if let ::std::option::Option::Some(daemon_tcp::Inner::TcpClose(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(daemon_tcp::Inner::TcpClose(TcpClose::new()));
        }
        match self.inner {
            ::std::option::Option::Some(daemon_tcp::Inner::TcpClose(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_tcp_close(&mut self) -> TcpClose {
        if self.has_tcp_close() {
            match self.inner.take() {
                ::std::option::Option::Some(daemon_tcp::Inner::TcpClose(v)) => v,
                _ => panic!(),
            }
        } else {
            TcpClose::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, NewTcpConnection>(
            "new_tcp_connection",
            DaemonTcp::has_new_tcp_connection,
            DaemonTcp::new_tcp_connection,
            DaemonTcp::mut_new_tcp_connection,
            DaemonTcp::set_new_tcp_connection,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, TcpData>(
            "tcp_data",
            DaemonTcp::has_tcp_data,
            DaemonTcp::tcp_data,
            DaemonTcp::mut_tcp_data,
            DaemonTcp::set_tcp_data,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, TcpClose>(
            "tcp_close",
            DaemonTcp::has_tcp_close,
            DaemonTcp::tcp_close,
            DaemonTcp::mut_tcp_close,
            DaemonTcp::set_tcp_close,
        ));
        oneofs.push(daemon_tcp::Inner::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DaemonTcp>(
            "DaemonTcp",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DaemonTcp {
    const NAME: &'static str = "DaemonTcp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.inner = ::std::option::Option::Some(daemon_tcp::Inner::NewTcpConnection(is.read_message()?));
                },
                18 => {
                    self.inner = ::std::option::Option::Some(daemon_tcp::Inner::TcpData(is.read_message()?));
                },
                26 => {
                    self.inner = ::std::option::Option::Some(daemon_tcp::Inner::TcpClose(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &daemon_tcp::Inner::NewTcpConnection(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &daemon_tcp::Inner::TcpData(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &daemon_tcp::Inner::TcpClose(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &daemon_tcp::Inner::NewTcpConnection(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
                &daemon_tcp::Inner::TcpData(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
                &daemon_tcp::Inner::TcpClose(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DaemonTcp {
        DaemonTcp::new()
    }

    fn clear(&mut self) {
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DaemonTcp {
        static instance: DaemonTcp = DaemonTcp {
            inner: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DaemonTcp {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DaemonTcp").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DaemonTcp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DaemonTcp {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `DaemonTcp`
pub mod daemon_tcp {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:protocol.DaemonTcp.inner)
    pub enum Inner {
        // @@protoc_insertion_point(oneof_field:protocol.DaemonTcp.new_tcp_connection)
        NewTcpConnection(super::NewTcpConnection),
        // @@protoc_insertion_point(oneof_field:protocol.DaemonTcp.tcp_data)
        TcpData(super::TcpData),
        // @@protoc_insertion_point(oneof_field:protocol.DaemonTcp.tcp_close)
        TcpClose(super::TcpClose),
    }

    impl ::protobuf::Oneof for Inner {
    }

    impl ::protobuf::OneofFull for Inner {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::DaemonTcp as ::protobuf::MessageFull>::descriptor().oneof_by_name("inner").unwrap()).clone()
        }
    }

    impl Inner {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Inner>("inner")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0fproto/tcp.proto\x12\x08protocol\"\xcf\x01\n\x10NewTcpConnection\
    \x12#\n\rconnection_id\x18\x01\x20\x01(\x04R\x0cconnectionId\x12%\n\x0er\
    emote_address\x18\x02\x20\x01(\x0cR\rremoteAddress\x12)\n\x10destination\
    _port\x18\x03\x20\x01(\x05R\x0fdestinationPort\x12\x1f\n\x0bsource_port\
    \x18\x04\x20\x01(\x05R\nsourcePort\x12#\n\rlocal_address\x18\x05\x20\x01\
    (\x0cR\x0clocalAddress\"D\n\x07TcpData\x12#\n\rconnection_id\x18\x01\x20\
    \x01(\x04R\x0cconnectionId\x12\x14\n\x05bytes\x18\x02\x20\x01(\x0cR\x05b\
    ytes\"/\n\x08TcpClose\x12#\n\rconnection_id\x18\x01\x20\x01(\x04R\x0ccon\
    nectionId\"\xa2\x01\n\x08LayerTcp\x12'\n\x0eport_subscribe\x18\x01\x20\
    \x01(\x05H\0R\rportSubscribe\x127\n\x16connection_unsubscribe\x18\x02\
    \x20\x01(\x04H\0R\x15connectionUnsubscribe\x12+\n\x10port_unsubscribe\
    \x18\x03\x20\x01(\x05H\0R\x0fportUnsubscribeB\x07\n\x05inner\"\xc3\x01\n\
    \tDaemonTcp\x12J\n\x12new_tcp_connection\x18\x01\x20\x01(\x0b2\x1a.proto\
    col.NewTcpConnectionH\0R\x10newTcpConnection\x12.\n\x08tcp_data\x18\x02\
    \x20\x01(\x0b2\x11.protocol.TcpDataH\0R\x07tcpData\x121\n\ttcp_close\x18\
    \x03\x20\x01(\x0b2\x12.protocol.TcpCloseH\0R\x08tcpCloseB\x07\n\x05inner\
    J\xce\x07\n\x06\x12\x04\0\0#\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\
    \x01\x02\x12\x03\x02\0\x11\n\n\n\x02\x04\0\x12\x04\x04\0\n\x01\n\n\n\x03\
    \x04\0\x01\x12\x03\x04\x08\x18\n\x0b\n\x04\x04\0\x02\0\x12\x03\x05\x08!\
    \n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x05\x08\x0e\n\x0c\n\x05\x04\0\x02\0\
    \x01\x12\x03\x05\x0f\x1c\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x05\x1f\x20\
    \n\x0b\n\x04\x04\0\x02\x01\x12\x03\x06\x08!\n\x0c\n\x05\x04\0\x02\x01\
    \x05\x12\x03\x06\x08\r\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x06\x0e\x1c\
    \n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x06\x1f\x20\n\x0b\n\x04\x04\0\x02\
    \x02\x12\x03\x07\x08#\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x07\x08\r\n\
    \x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x07\x0e\x1e\n\x0c\n\x05\x04\0\x02\
    \x02\x03\x12\x03\x07!\"\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x08\x08\x1e\n\
    \x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x08\x08\r\n\x0c\n\x05\x04\0\x02\x03\
    \x01\x12\x03\x08\x0e\x19\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x08\x1c\
    \x1d\n\x0b\n\x04\x04\0\x02\x04\x12\x03\t\x08\x20\n\x0c\n\x05\x04\0\x02\
    \x04\x05\x12\x03\t\x08\r\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\t\x0e\x1b\
    \n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\t\x1e\x1f\n\n\n\x02\x04\x01\x12\
    \x04\x0c\0\x0f\x01\n\n\n\x03\x04\x01\x01\x12\x03\x0c\x08\x0f\n\x0b\n\x04\
    \x04\x01\x02\0\x12\x03\r\x08!\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\r\
    \x08\x0e\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\r\x0f\x1c\n\x0c\n\x05\x04\
    \x01\x02\0\x03\x12\x03\r\x1f\x20\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\x0e\
    \x08\x18\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x0e\x08\r\n\x0c\n\x05\
    \x04\x01\x02\x01\x01\x12\x03\x0e\x0e\x13\n\x0c\n\x05\x04\x01\x02\x01\x03\
    \x12\x03\x0e\x16\x17\n\n\n\x02\x04\x02\x12\x04\x11\0\x13\x01\n\n\n\x03\
    \x04\x02\x01\x12\x03\x11\x08\x10\n\x0b\n\x04\x04\x02\x02\0\x12\x03\x12\
    \x08!\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\x12\x08\x0e\n\x0c\n\x05\x04\
    \x02\x02\0\x01\x12\x03\x12\x0f\x1c\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03\
    \x12\x1f\x20\n\n\n\x02\x04\x03\x12\x04\x15\0\x1b\x01\n\n\n\x03\x04\x03\
    \x01\x12\x03\x15\x08\x10\n\x0c\n\x04\x04\x03\x08\0\x12\x04\x16\x08\x1a\t\
    \n\x0c\n\x05\x04\x03\x08\0\x01\x12\x03\x16\x0e\x13\n\x0b\n\x04\x04\x03\
    \x02\0\x12\x03\x17\x10)\n\x0c\n\x05\x04\x03\x02\0\x05\x12\x03\x17\x10\
    \x15\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03\x17\x16$\n\x0c\n\x05\x04\x03\
    \x02\0\x03\x12\x03\x17'(\n\x0b\n\x04\x04\x03\x02\x01\x12\x03\x18\x102\n\
    \x0c\n\x05\x04\x03\x02\x01\x05\x12\x03\x18\x10\x16\n\x0c\n\x05\x04\x03\
    \x02\x01\x01\x12\x03\x18\x17-\n\x0c\n\x05\x04\x03\x02\x01\x03\x12\x03\
    \x1801\n\x0b\n\x04\x04\x03\x02\x02\x12\x03\x19\x10+\n\x0c\n\x05\x04\x03\
    \x02\x02\x05\x12\x03\x19\x10\x15\n\x0c\n\x05\x04\x03\x02\x02\x01\x12\x03\
    \x19\x16&\n\x0c\n\x05\x04\x03\x02\x02\x03\x12\x03\x19)*\n\n\n\x02\x04\
    \x04\x12\x04\x1d\0#\x01\n\n\n\x03\x04\x04\x01\x12\x03\x1d\x08\x11\n\x0c\
    \n\x04\x04\x04\x08\0\x12\x04\x1e\x08\"\t\n\x0c\n\x05\x04\x04\x08\0\x01\
    \x12\x03\x1e\x0e\x13\n\x0b\n\x04\x04\x04\x02\0\x12\x03\x1f\x108\n\x0c\n\
    \x05\x04\x04\x02\0\x06\x12\x03\x1f\x10\x20\n\x0c\n\x05\x04\x04\x02\0\x01\
    \x12\x03\x1f!3\n\x0c\n\x05\x04\x04\x02\0\x03\x12\x03\x1f67\n\x0b\n\x04\
    \x04\x04\x02\x01\x12\x03\x20\x10%\n\x0c\n\x05\x04\x04\x02\x01\x06\x12\
    \x03\x20\x10\x17\n\x0c\n\x05\x04\x04\x02\x01\x01\x12\x03\x20\x18\x20\n\
    \x0c\n\x05\x04\x04\x02\x01\x03\x12\x03\x20#$\n\x0b\n\x04\x04\x04\x02\x02\
    \x12\x03!\x10'\n\x0c\n\x05\x04\x04\x02\x02\x06\x12\x03!\x10\x18\n\x0c\n\
    \x05\x04\x04\x02\x02\x01\x12\x03!\x19\"\n\x0c\n\x05\x04\x04\x02\x02\x03\
    \x12\x03!%&b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(NewTcpConnection::generated_message_descriptor_data());
            messages.push(TcpData::generated_message_descriptor_data());
            messages.push(TcpClose::generated_message_descriptor_data());
            messages.push(LayerTcp::generated_message_descriptor_data());
            messages.push(DaemonTcp::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
